-- 7. Compute the difference between the average stars of businesses considered 'good for dinner' with a (1)
-- "divey" and (2) an "upscale" ambience. Name the column of the result 'DIFFERENCE_OF_AVERAGES'

SELECT
  (
    SELECT AVG(B.STARS)
    FROM BUSINESS B
    JOIN BUSINESS_GOOD_FOR_MEAL BGFM ON B.BUSINESS_ID = BGFM.BUSINESS_ID
    JOIN GOOD_FOR_MEAL GFM ON BGFM.GOOD_FOR_MEAL_ID = GFM.GOOD_FOR_MEAL_ID
    JOIN BUSINESS_AMBIANCE BA ON B.BUSINESS_ID = BA.BUSINESS_ID
    JOIN AMBIANCE A ON BA.AMBIANCE_ID = A.AMBIANCE_ID
    WHERE GFM.GOOD_FOR_MEAL_DESCRIPTION = 'dinner'
    AND A.AMBIANCE_DESCRIPTION = 'divey'
  ) - 
  (
    SELECT AVG(B.STARS)
    FROM BUSINESS B
    JOIN BUSINESS_GOOD_FOR_MEAL BGFM ON B.BUSINESS_ID = BGFM.BUSINESS_ID
    JOIN GOOD_FOR_MEAL GFM ON BGFM.GOOD_FOR_MEAL_ID = GFM.GOOD_FOR_MEAL_ID
    JOIN BUSINESS_AMBIANCE BA ON B.BUSINESS_ID = BA.BUSINESS_ID
    JOIN AMBIANCE A ON BA.AMBIANCE_ID = A.AMBIANCE_ID
    WHERE GFM.GOOD_FOR_MEAL_DESCRIPTION = 'dinner'
    AND A.AMBIANCE_DESCRIPTION = 'upscale'
  ) AS DIFFERENCE_OF_AVERAGES
FROM DUAL;
